### ISSUE TITLE
Invalid Extension Version Param when extension requests assets

### ISSUE THREAD

**Issue by kacesensitive** [meslzy/twitch-extensions-boilerplate#1]
First off, thanks so much for making this boilerplate!!! @meslzy 

One thing i ran into recently was when i moved to a hosted test, zipped up the contents in the /dist folder and uploaded the assets was this.

![Screenshot 2024-02-22 at 10 02 24 AM](https://github.com/meslzy/twitch-extensions-boilerplate/assets/17398470/6800b6e7-6d5e-4234-a688-0427c63e1d33)

Twitch seems to add a version tag to the url, like
`https://c1r7ffd0vz5pxlih0o3g3xr3pw26ye.ext-twitch.tv/c1r7ffd0vz5pxlih0o3g3xr3pw26ye/0.0.1/7304025a6ed75a7e90ea0dc4f6786bf5/panel.html?anchor=panel&language=en&locale=en-US&mode=viewer&state=hosted_test&platform=web`

But when it requests the assets it reaches for 
`https://c1r7ffd0vz5pxlih0o3g3xr3pw26ye.ext-twitch.tv/assets/panel-9e4ec65d.js`
Which fails due to
**Invalid Extension Version Param**

Any ideas?

**Comment by meslzy** [comment]
Well, The base URL is this
`https://c1r7ffd0vz5pxlih0o3g3xr3pw26ye.ext-twitch.tv/`

but when twitch load the html file it loads it from 
`https://c1r7ffd0vz5pxlih0o3g3xr3pw26ye.ext-twitch.tv/c1r7ffd0vz5pxlih0o3g3xr3pw26ye/0.0.1/7304025a6ed75a7e90ea0dc4f6786bf5/panel.html`

And by default Vite.js bundle and set the base to `/`

So your CSS file will be hosted from the root URL which is /

To solve this issue ill just use this [option](https://vitejs.dev/config/shared-options.html#base)

And set it to "./" so it use the current URL

You maybe want to use diff value for development or prod.

**Comment by meslzy** [comment]
I'll update the boilerplate and test it out, I hope you can give me time to do it.

**Comment by meslzy** [comment]
I have updated the boilerplate, Please try to sync your `vite.config.ts` with mine [vite.config.ts](https://github.com/meslzy/twitch-extensions-boilerplate/blob/main/vite.config.ts)
